# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "*" ]       # Execute every push
  pull_request:
    branches: [ "*" ]       # Execute every PR

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22' ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Verify dependencies
      run: go mod tidy && git diff --exit-code

    - name: Check code formatting
      run: gofmt -s -l .

    - name: Build
      run: go build -v ./...

    - name: Run tests with coverage
      run: go test -v -coverprofile=coverage.out ./...

    - name: Create go.work
      run: |
        go work init
        go work use .
        go work use ./examples/memory-store
    
    - name: Sync workspace
      run: go work sync

    - name: Test Examples
      working-directory: ./examples/memory-store
      run: |
        go work use ../../
        go test -v ./...
    

